# Site settings
title: Atelier Armure
tagline: 
description: 
image: /assets/images/image.png
url: https://ajuliette.github.io/
github_url: https://ajuliette.github.io/
resume: false
author: Juliette Audema
lang: fr-FR

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap