# Site settings
title: Armure
tagline: site-tagline
description: site-description
image: /assets/images/image.png
url: /
github_url: https://ajuliette.github.io/
resume: false
author: Juliette Audema
lang: fr-FR

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap